### ISSUE TITLE
Должен ли темплейт компонента повторять DOM структуру виджета на сайте?

### ISSUE THREAD

**Issue by etovolchanka** [turboext/components#35]
На странице сайта, которую я хочу отдавать в Турбо есть интерактивный виджет. Я пишу кастомный компонент, повторяющий его функционал. Вопрос:
Должен ли отрендеренный компонент повторять структуру оригинального виджета или достаточно того, что они выглядят одинаково и отображают одинаковый контент? Не хотелось бы получить предупреждение о несоответствии контента. Какой вообще допускается разлет?

**Comment by notary** [comment]
Привет, спасибо за вопрос. Достаточно того, чтобы виджеты выглядели одинаково и отображали одинаковый контент.

**Comment by etovolchanka** [comment]
Спасибо!
