### ISSUE TITLE
Ограничения на работу с DOM

### ISSUE THREAD

**Issue by rlshukhov** [turboext/components#40]
Здравствуйте!

Есть ли какие либо ограничения на работу с DOM страницы?

Конкретно интересует:
- Отправка JSONP запросов к сторонним доменам
- Замена текста определенных элементов страницы (в рамках турбо-страницы)

**Comment by notary** [comment]
Добрый день!

Спасибо за вопрос. Ограничений на взаимодействие с DOM в целом нет. 
Что касается JSONP предпочтительным способом является отправка AJAX запросов, так как JSONP подразумевает вставку скриптов со сторонних источников, в связи с чем возможно использовать только как встраиваемый виджет https://github.com/turboext/components#%D0%B2%D1%81%D1%82%D1%80%D0%B0%D0%B8%D0%B2%D0%B0%D0%B5%D0%BC%D1%8B%D0%B5-%D0%B2%D0%B8%D0%B4%D0%B6%D0%B5%D1%82%D1%8B-embed-widgets
