### ISSUE TITLE
На сайтах не отображается компонент

### ISSUE THREAD

**Issue by DenyHF** [turboext/components#99]
Добрый день
Существует проблема отображения компонента ExtLentainformWidget на живых [сайтах](https://yandex.ru/turbo/sovsport.ru/s/football/news/2:989875), при чем в отладке все отображается корректно.
<img width="1158" alt="4" src="https://user-images.githubusercontent.com/11006983/119969142-dbf2af00-bfb6-11eb-8e5a-b3b0cc3e30b1.png">

С чем связана данная проблема?

**Comment by muftiev** [comment]
Добрый день!
Спасибо за обращение. В ближайшее время мы обязательно проверим эту проблему

**Comment by sklznv** [comment]
Ошибки со стороны Турбо нет. У площадки включен автопарсер, а все фиды отключены. Автопарсер собирает только конетент. Наша автоматика строит Турбо-страницы самостоятельно, без виджета и расставляет только блоки рекламы с помощью нашей авторасстанвоки. Чтобы виджет появился, нужно включить RSS каналы.
